FORMAT: 1A

# Agenda
Agenda API is a *short texts saving* service similar to its physical paper presence in your school.

# Group Login
allow the teacher to login **Agenda API**

## login [/login]
### Login [POST]
+ Request (application/json)

        { "username": "jad", "password": "4234" ,"type": "parent" }

+ Response 200 (application/json)

        {
          "success": true,
          "error": 0,
          "message": "",
          "data": [
            {
              "id": 5,
              "name": "مهند",
              "classId": 5,
              "className": "الثّاني ابتدائي",
              "sectionId": 9,
              "sectionName": "ب",
              "languageId": 1,
              "languageName": "English"
            },
            {
              "id": 9,
              "name": "زينب",
              "classId": 5,
              "className": "الثّاني ابتدائي",
              "sectionId": 8,
              "sectionName": "أ",
              "languageId": 1,
              "languageName": "English"
            },
            {
              "id": 19,
              "name": "محمد",
              "classId": 5,
              "className": "الثّاني ابتدائي",
              "sectionId": 8,
              "sectionName": "أ",
              "languageId": 1,
              "languageName": "English"
            }
          ]
        }

# Group Homeworks
manage the homeworks in **Agenda API**
## homeworks Collection [/homeworks/{id}/{date}]
### List all homeworks [GET]
+ Response 200 (application/json)

        [{
          "id": 1,
          "homework": "Jogging in park",
          "teacher": "Jhon amigo",
          "course": "Maths",
          "date": "2015-12-04", 
          "documents": "file.png"
        }, {
          "id": 2,
          "homework": "Do not do your homework",
          "teacher": "Jhon amigo",
          "course": "Physics",
          "date": "2015-12-04", 
          "documents": "file.png"
        }, {
          "id": 3,
          "homework": "You love the man ;)",
          "teacher": "Jhone the ripper :P",
          "course": "Chemistry",
          "date": "2015-12-04", 
          "documents": "file.png"
        }]
        
## search homeworks [/homeworks/search]
### List homeworks by options [POST]
+ Request (application/json)

        {
          "courseId": 2,
          "classId": 1,
          "id": 1023,
          "sectionId": 2,
          "fromDate": "2015-03-15",
          "toDate": "2015-03-15"
        }
        
+ Response 200 (application/json)

        [{
          "id": 1,
          "homework": "Jogging in park",
          "teacher": "Jhon amigo",
          "course": "Maths",
          "date": "2015-12-04", 
          "documents": "file.png"
        }, {
          "id": 2,
          "homework": "Do not do your homework",
          "teacher": "Jhon amigo",
          "course": "Physics",
          "date": "2015-12-04", 
          "documents": "file.png"
        }, {
          "id": 3,
          "homework": "You love the man ;)",
          "teacher": "Jhone the ripper :P",
          "course": "Chemistry",
          "date": "2015-12-04", 
          "documents": "file.png"
        }]
        
##  Add Homework [/homeworks/add]
### Create a Homework [POST]


+ Request (application/json)

        {
          "id": 3,
          "classId": 4,
          "sectionId": 1,
          "courseId": 2,
          "homeworks": [
            {
              "date": "2015-02-12",
              "homework": "devoir numero 5 dans la page 12", 
              "documents": "file.png"
            },
            {
              "date": "2015-02-12",
              "homework": "devoir numero 5 dans la page 12", 
              "documents": "file.png"
            },
            {
              "date": "2015-02-14",
              "homework": "devoir numero 5 dans la page 12", 
              "documents": "file.png"
            },
            {
              "date": "2015-02-15",
              "homework": "devoir numero 5 dans la page 12", 
              "documents": "file.png"
            },
            {
              "date": "2015-02-20",
              "homework": "Examen de francais, par coeur!", 
              "documents": "file.png"
            },
            {
              "date": "2015-02-12",
              "homework": "Recitation ecrite.", 
              "documents": "file.png"
            },
            {
              "date": "2015-02-12",
              "homework": "devoir numero 5 dans la page 12", 
              "documents": "file.png"
            }
          ]
        }

+ Response 200 (application/json)

    + Headers

            Set-Cookie: ELMAuth=; path=/elmst; expires=Mon, 30-Jul-2012 09:12:42 GMT; secure; HttpOnly, ELMAuthSST={super-secured-token}; path=/elmst/account; secure; HttpOnly

    + Body
    
    
            {
                "message": "",
                "code": 0,
                "success": true,
                "data": null
            }
            
            
            
##  Save Parents Response [/Parents/Edit]
### Create a Homework [POST]


+ Request (application/json)

        [{
              "agendaId": 1,
              "studentId": 1,
              "isDone": true,
              "comments": "Comment here"
            },
        {
              "agendaId": 2,
              "studentId": 2,
              "isDone": true,
              "comments": "Comment here"
            },
            {
              "agendaId": 3,
              "studentId": 4,
              "isDone": true,
              "comments": "Comment here"
            }]

+ Response 200 (application/json)

    + Headers

            Set-Cookie: ELMAuth=; path=/elmst; expires=Mon, 30-Jul-2012 09:12:42 GMT; secure; HttpOnly, ELMAuthSST={super-secured-token}; path=/elmst/account; secure; HttpOnly

    + Body
    
    
            {
                "message": "",
                "code": 0,
                "success": true,
                "data": null
            }
   

   

